export const CHANGE_CURRENT_SONG = 'song/CHANGE_CURRENT_SONG'
export const CHANGE_SONG_INFO = 'song/CHANGE_SONG_INFO'
export const CHANGE_SIMILAR_SONG = 'song/CHANGE_SIMILAR_SONG'
export const CHANGE_SIMILAR_LIST = 'song/CHANGE_SIMILAR_LIST'